class CurrencyData {
  static final Map<String, String> currencies = {
    'AFN': 'Afghan afghani',
    'ALL': 'Albanian lek',
    'DZD': 'Algerian dinar',
    'AOA': 'Angolan kwanza',
    'ARS': 'Argentine peso',
    'AMD': 'Armenian dram',
    'AUD': 'Australian dollar',
    'AZN': 'Azerbaijani manat',
    'BSD': 'Bahamian dollar',
    'BHD': 'Bahraini dinar',
    'BDT': 'Bangladeshi taka',
    'BBD': 'Barbadian dollar',
    'BYN': 'Belarusian ruble',
    'BZD': 'Belize dollar',
    'BMD': 'Bermudian dollar',
    'BTN': 'Bhutanese ngultrum',
    'BOB': 'Bolivian boliviano',
    'BAM': 'Bosnian convertible mark',
    'BWP': 'Botswana pula',
    'BRL': 'Brazilian real',
    'BND': 'Brunei dollar',
    'BGN': 'Bulgarian lev',
    'BIF': 'Burundian franc',
    'KHR': 'Cambodian riel',
    'CAD': 'Canadian dollar',
    'CVE': 'Cape Verdean escudo',
    'XAF': 'CFA franc BEAC',
    'XOF': 'CFA franc BCEAO',
    'CLP': 'Chilean peso',
    'CNY': 'Chinese yuan',
    'COP': 'Colombian peso',
    'KMF': 'Comorian franc',
    'CDF': 'Congolese franc',
    'CRC': 'Costa Rican colón',
    'CUP': 'Cuban peso',
    'CZK': 'Czech koruna',
    'DKK': 'Danish krone',
    'DJF': 'Djiboutian franc',
    'DOP': 'Dominican peso',
    'EGP': 'Egyptian pound',
    'ERN': 'Eritrean nakfa',
    'ETB': 'Ethiopian birr',
    'EUR': 'Euro',
    'FJD': 'Fijian dollar',
    'GMD': 'Gambian dalasi',
    'GEL': 'Georgian lari',
    'GHS': 'Ghanaian cedi',
    'GTQ': 'Guatemalan quetzal',
    'GNF': 'Guinean franc',
    'GYD': 'Guyanese dollar',
    'HTG': 'Haitian gourde',
    'HNL': 'Honduran lempira',
    'HKD': 'Hong Kong dollar',
    'HUF': 'Hungarian forint',
    'ISK': 'Icelandic króna',
    'INR': 'Indian rupee',
    'IDR': 'Indonesian rupiah',
    'IRR': 'Iranian rial',
    'IQD': 'Iraqi dinar',
    'ILS': 'Israeli new shekel',
    'JMD': 'Jamaican dollar',
    'JPY': 'Japanese yen',
    'JOD': 'Jordanian dinar',
    'KZT': 'Kazakhstani tenge',
    'KES': 'Kenyan shilling',
    'KWD': 'Kuwaiti dinar',
    'LAK': 'Lao kip',
    'LBP': 'Lebanese pound',
    'LSL': 'Lesotho loti',
    'LRD': 'Liberian dollar',
    'LYD': 'Libyan dinar',
    'MGA': 'Malagasy ariary',
    'MWK': 'Malawian kwacha',
    'MYR': 'Malaysian ringgit',
    'MVR': 'Maldivian rufiyaa',
    'MRU': 'Mauritanian ouguiya',
    'MUR': 'Mauritian rupee',
    'MXN': 'Mexican peso',
    'MDL': 'Moldovan leu',
    'MNT': 'Mongolian tögrög',
    'MAD': 'Moroccan dirham',
    'MZN': 'Mozambican metical',
    'MMK': 'Myanmar kyat',
    'NAD': 'Namibian dollar',
    'NPR': 'Nepalese rupee',
    'NZD': 'New Zealand dollar',
    'NIO': 'Nicaraguan córdoba',
    'NGN': 'Nigerian naira',
    'KPW': 'North Korean won',
    'NOK': 'Norwegian krone',
    'OMR': 'Omani rial',
    'PKR': 'Pakistani rupee',
    'PAB': 'Panamanian balboa',
    'PGK': 'Papua New Guinean kina',
    'PYG': 'Paraguayan guaraní',
    'PEN': 'Peruvian sol',
    'PHP': 'Philippine peso',
    'PLN': 'Polish złoty',
    'GBP': 'Pound sterling',
    'QAR': 'Qatari riyal',
    'RON': 'Romanian leu',
    'RUB': 'Russian ruble',
    'RWF': 'Rwandan franc',
    'SAR': 'Saudi riyal',
    'RSD': 'Serbian dinar',
    'SCR': 'Seychellois rupee',
    'SLE': 'Sierra Leonean leone',
    'SGD': 'Singapore dollar',
    'SBD': 'Solomon Islands dollar',
    'SOS': 'Somali shilling',
    'ZAR': 'South African rand',
    'KRW': 'South Korean won',
    'LKR': 'Sri Lankan rupee',
    'SDG': 'Sudanese pound',
    'SRD': 'Surinamese dollar',
    'SEK': 'Swedish krona',
    'CHF': 'Swiss franc',
    'SYP': 'Syrian pound',
    'TJS': 'Tajikistani somoni',
    'TZS': 'Tanzanian shilling',
    'THB': 'Thai baht',
    'TOP': 'Tongan paʻanga',
    'TTD': 'Trinidad and Tobago dollar',
    'TND': 'Tunisian dinar',
    'TRY': 'Turkish lira',
    'UGX': 'Ugandan shilling',
    'UAH': 'Ukrainian hryvnia',
    'AED': 'UAE dirham',
    'USD': 'US dollar',
    'UYU': 'Uruguayan peso',
    'UZS': 'Uzbekistani soʻm',
    'VUV': 'Vanuatu vatu',
    'VND': 'Vietnamese đồng',
    'YER': 'Yemeni rial',
    'ZMW': 'Zambian kwacha',
    'ZWL': 'Zimbabwean dollar',
  };

  static final Map<String, String> currencySymbols = {
    'AFN': '؋',
    'ALL': 'L',
    'DZD': 'د.ج',
    'AOA': 'Kz',
    'ARS': '\$',
    'AMD': '֏',
    'AUD': '\$',
    'AZN': '₼',
    'BSD': '\$',
    'BHD': '.د.ب',
    'BDT': '৳',
    'BBD': '\$',
    'BYN': 'Br',
    'BZD': '\$',
    'BMD': '\$',
    'BTN': 'Nu.',
    'BOB': 'Bs.',
    'BAM': 'KM',
    'BWP': 'P',
    'BRL': 'R\$',
    'BND': '\$',
    'BGN': 'лв',
    'BIF': 'Fr',
    'KHR': '៛',
    'CAD': '\$',
    'CVE': 'Esc',
    'XAF': 'Fr',
    'XOF': 'Fr',
    'CLP': '\$',
    'CNY': '¥',
    'COP': '\$',
    'KMF': 'Fr',
    'CDF': 'Fr',
    'CRC': '₡',
    'CUP': '\$',
    'CZK': 'Kč',
    'DKK': 'kr',
    'DJF': 'Fr',
    'DOP': 'RD\$',
    'EGP': '£',
    'ERN': 'Nfk',
    'ETB': 'Br',
    'EUR': '€',
    'FJD': '\$',
    'GMD': 'D',
    'GEL': '₾',
    'GHS': '₵',
    'GTQ': 'Q',
    'GNF': 'Fr',
    'GYD': '\$',
    'HTG': 'G',
    'HNL': 'L',
    'HKD': '\$',
    'HUF': 'Ft',
    'ISK': 'kr',
    'INR': '₹',
    'IDR': 'Rp',
    'IRR': '﷼',
    'IQD': 'ع.d',
    'ILS': '₪',
    'JMD': '\$',
    'JPY': '¥',
    'JOD': 'د.ا',
    'KZT': '₸',
    'KES': 'Sh',
    'KWD': 'د.ك',
    'LAK': '₭',
    'LBP': 'ل.ل',
    'LSL': 'L',
    'LRD': '\$',
    'LYD': 'ل.د',
    'MGA': 'Ar',
    'MWK': 'MK',
    'MYR': 'RM',
    'MVR': '.ރ',
    'MRU': 'UM',
    'MUR': '₨',
    'MXN': '\$',
    'MDL': 'L',
    'MNT': '₮',
    'MAD': 'د.م.',
    'MZN': 'MT',
    'MMK': 'Ks',
    'NAD': '\$',
    'NPR': '₨',
    'NZD': '\$',
    'NIO': 'C\$',
    'NGN': '₦',
    'KPW': '₩',
    'NOK': 'kr',
    'OMR': 'ر.ع.',
    'PKR': '₨',
    'PAB': 'B/.',
    'PGK': 'K',
    'PYG': '₲',
    'PEN': 'S/',
    'PHP': '₱',
    'PLN': 'zł',
    'GBP': '£',
    'QAR': 'ر.ق',
    'RON': 'lei',
    'RUB': '₽',
    'RWF': 'Fr',
    'SAR': 'ر.س',
    'RSD': 'дин.',
    'SCR': '₨',
    'SLE': 'Le',
    'SGD': '\$',
    'SBD': '\$',
    'SOS': 'Sh',
    'ZAR': 'R',
    'KRW': '₩',
    'LKR': 'Rs',
    'SDG': 'ج.س.',
    'SRD': '\$',
    'SEK': 'kr',
    'CHF': 'Fr',
    'SYP': '£',
    'TJS': 'ЅМ',
    'TZS': 'Sh',
    'THB': '฿',
    'TOP': 'T\$',
    'TTD': '\$',
    'TND': 'د.ت',
    'TRY': '₺',
    'UGX': 'Sh',
    'UAH': '₴',
    'AED': 'د.إ',
    'USD': '\$',
    'UYU': '\$',
    'UZS': 'soʻm',
    'VUV': 'Vt',
    'VND': '₫',
    'YER': '﷼',
    'ZMW': 'ZK',
    'ZWL': '\$',
  };
}
